--
--ER/Studio 7.0 SQL Code Generation
-- Company :      yinhoo
-- Project :      zycs.DM1
-- Author :       roger
--
-- Date Created : Wednesday, November 25, 2009 11:32:22
-- Target DBMS : Oracle 10g
--

DROP TABLE CT_ENT_AREA CASCADE CONSTRAINTS
;
DROP TABLE CT_ENT_BRANCH_PRODUCT CASCADE CONSTRAINTS
;
DROP TABLE CT_ENT_ENTERPRISE CASCADE CONSTRAINTS
;
DROP TABLE CT_ENT_TRADE_RELATION CASCADE CONSTRAINTS
;
DROP TABLE CT_PRO_CATEGORY CASCADE CONSTRAINTS
;
DROP TABLE CT_PRO_CATEGORY_EXTEND CASCADE CONSTRAINTS
;
DROP TABLE CT_PRO_CORE_ATTRIBUTE CASCADE CONSTRAINTS
;
DROP TABLE CT_PRO_EXTEND_ATTRIBUTE CASCADE CONSTRAINTS
;
DROP TABLE CT_PRO_EXTEND_ATTRIBUTE_VALUE CASCADE CONSTRAINTS
;
DROP TABLE CT_PRO_MEASURE_UNIT CASCADE CONSTRAINTS
;
DROP TABLE CT_PRO_PAPER CASCADE CONSTRAINTS
;
DROP TABLE CT_PRO_PRODUCT CASCADE CONSTRAINTS
;
DROP TABLE CT_PRO_PRODUCT_UNIT_SETTING CASCADE CONSTRAINTS
;
DROP TABLE CT_PRO_PULP CASCADE CONSTRAINTS
;
DROP TABLE CT_SYS_BASECODE CASCADE CONSTRAINTS
;
DROP TABLE CT_SYS_PARAMETER CASCADE CONSTRAINTS
;
DROP TABLE CT_USER_ADMIN CASCADE CONSTRAINTS
;
DROP TABLE CT_USER_FUNCTION CASCADE CONSTRAINTS
;
DROP TABLE CT_USER_FUNCTION_ACTION CASCADE CONSTRAINTS
;
DROP TABLE CT_USER_ROLE CASCADE CONSTRAINTS
;
DROP TABLE CT_USER_ROLE_FUNCTION CASCADE CONSTRAINTS
;
DROP TABLE CT_USER_USER CASCADE CONSTRAINTS
;
DROP TABLE CT_USER_USER_ROLE CASCADE CONSTRAINTS
;
-- 
-- TABLE: CT_ENT_AREA 
--

CREATE TABLE CT_ENT_AREA(
    FID                 NUMBER(19, 0)     NOT NULL,
    CODE                VARCHAR2(32)      NOT NULL,
    DESCRIPTION         VARCHAR2(4000),
    FULL_CODE           VARCHAR2(255),
    LAST_UPDATE_DATE    TIMESTAMP(6),
    NAME                VARCHAR2(64),
    PARENT_ID           NUMBER(19, 0),
    CONSTRAINT CPK_ENT_AREA PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_ENT_BRANCH_PRODUCT 
--

CREATE TABLE CT_ENT_BRANCH_PRODUCT(
    FID             NUMBER(19, 0)    NOT NULL,
    EXPIRED_DATE    TIMESTAMP(6),
    BRANCH_ID       NUMBER(19, 0)    NOT NULL,
    PRODUCT_ID      NUMBER(19, 0)    NOT NULL,
    CONSTRAINT CPK_ENT_BRANCH_PRODUCT PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_ENT_ENTERPRISE 
--

CREATE TABLE CT_ENT_ENTERPRISE(
    FID                 NUMBER(19, 0)     NOT NULL,
    ADDRESS             VARCHAR2(255),
    CODE                VARCHAR2(32)      NOT NULL,
    DESCRIPTION         VARCHAR2(4000),
    EMAIL               VARCHAR2(64),
    IS_ENABLED          NUMBER(1, 0)      NOT NULL,
    FAX                 VARCHAR2(32),
    ENT_KIND            VARCHAR2(32),
    LAST_UPDATE_DATE    TIMESTAMP(6),
    LINK_MAN            VARCHAR2(64),
    NAME                VARCHAR2(64)      NOT NULL,
    POSTCODE            VARCHAR2(16),
    TELEPHONE           VARCHAR2(32),
    ENT_TYPE            VARCHAR2(32),
    LOCATION_ID         NUMBER(19, 0),
    CONSTRAINT CPK_ENT_ENTERPRISE PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_ENT_TRADE_RELATION 
--

CREATE TABLE CT_ENT_TRADE_RELATION(
    FID             NUMBER(19, 0)    NOT NULL,
    EXPIRED_DATE    TIMESTAMP(6),
    BRANCH_ID       NUMBER(19, 0)    NOT NULL,
    PARTNER_ID      NUMBER(19, 0)    NOT NULL,
    CONSTRAINT CPK_ENT_TRADE_RELATION PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_PRO_CATEGORY 
--

CREATE TABLE CT_PRO_CATEGORY(
    FID                 NUMBER(19, 0)     NOT NULL,
    CODE                VARCHAR2(32)      NOT NULL,
    DESCRIPTION         VARCHAR2(4000),
    FULL_CODE           VARCHAR2(255),
    LAST_UPDATE_DATE    TIMESTAMP(6),
    NAME                VARCHAR2(64)      NOT NULL,
    CAT_TYPE            VARCHAR2(32)      NOT NULL,
    PARENT_ID           NUMBER(19, 0),
    CONSTRAINT CPK_PRO_CATEGORY PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_PRO_CATEGORY_EXTEND 
--

CREATE TABLE CT_PRO_CATEGORY_EXTEND(
    CT_PRO_CATEGORY_FID        NUMBER(19, 0)    NOT NULL,
    EXTENDATTRIBUTELIST_FID    NUMBER(19, 0)    NOT NULL
)
;



-- 
-- TABLE: CT_PRO_CORE_ATTRIBUTE 
--

CREATE TABLE CT_PRO_CORE_ATTRIBUTE(
    FID               NUMBER(19, 0)     NOT NULL,
    ATTRIBUTE_TYPE    VARCHAR2(32),
    CODE              VARCHAR2(32)      NOT NULL,
    DEFAULT_VALUE     VARCHAR2(255),
    DESCRIPTION       VARCHAR2(4000),
    MAX_LENGTH        NUMBER(10, 0)     NOT NULL,
    NAME              VARCHAR2(64)      NOT NULL,
    PROPERTY_NAME     VARCHAR2(64),
    VALUE_TYPE        VARCHAR2(32),
    CONSTRAINT CPK_PRO_CORE_ATTRIBUTE PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_PRO_EXTEND_ATTRIBUTE 
--

CREATE TABLE CT_PRO_EXTEND_ATTRIBUTE(
    FID              NUMBER(19, 0)     NOT NULL,
    CODE             VARCHAR2(32)      NOT NULL,
    DEFAULT_VALUE    VARCHAR2(255),
    DESCRIPTION      VARCHAR2(4000),
    IS_ENBALED       NUMBER(1, 0)      NOT NULL,
    MAX_LENGTH       NUMBER(10, 0)     NOT NULL,
    NAME             VARCHAR2(64)      NOT NULL,
    VALUE_TYPE       VARCHAR2(32),
    CONSTRAINT CPK_PRO_EXTEND_ATTRIBUTE PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_PRO_EXTEND_ATTRIBUTE_VALUE 
--

CREATE TABLE CT_PRO_EXTEND_ATTRIBUTE_VALUE(
    FID                NUMBER(19, 0)    NOT NULL,
    ATTRIBUTE_VALUE    VARCHAR2(255),
    ATTRIBUTE_ID       NUMBER(19, 0)    NOT NULL,
    PRODUCT_ID         NUMBER(19, 0)    NOT NULL,
    CONSTRAINT CPK_PRO_EXTEND_ATTRIBUTE_VALUE PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_PRO_MEASURE_UNIT 
--

CREATE TABLE CT_PRO_MEASURE_UNIT(
    FID             NUMBER(19, 0)     NOT NULL,
    IS_BENCHMARK    NUMBER(1, 0)      NOT NULL,
    CODE            VARCHAR2(32)      NOT NULL,
    DESCRIPTION     VARCHAR2(4000),
    IS_ENBALED      NUMBER(1, 0)      NOT NULL,
    NAME            VARCHAR2(64)      NOT NULL,
    CONSTRAINT CPK_PRO_MEASURE_UNIT PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_PRO_PAPER 
--

CREATE TABLE CT_PRO_PAPER(
    BRAND           VARCHAR2(64)     NOT NULL,
    GRADE           VARCHAR2(64)     NOT NULL,
    GRAMMAGE        VARCHAR2(64)     NOT NULL,
    PRODUCT_NAME    VARCHAR2(64)     NOT NULL,
    SPEC            VARCHAR2(64)     NOT NULL,
    FID             NUMBER(19, 0)    NOT NULL,
    CONSTRAINT CPK_PRO_PAPER PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_PRO_PRODUCT 
--

CREATE TABLE CT_PRO_PRODUCT(
    FID                 NUMBER(19, 0)     NOT NULL,
    CODE                VARCHAR2(32)      NOT NULL,
    DESCRIPTION         VARCHAR2(4000),
    FULL_NAME           VARCHAR2(255)     NOT NULL,
    GTIN_NUMBER         VARCHAR2(32),
    LAST_UPDATE_DATE    TIMESTAMP(6),
    NET_CODE            VARCHAR2(32),
    SUPPLIER_CODE       VARCHAR2(32),
    SUPPLIER_NAME       VARCHAR2(255),
    SUPPLIER_NUMBER     VARCHAR2(32),
    THUMBNAIL_URL       VARCHAR2(255),
    CATEGORY_ID         NUMBER(19, 0),
    CONSTRAINT CPK_PRO_PRODUCT PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_PRO_PRODUCT_UNIT_SETTING 
--

CREATE TABLE CT_PRO_PRODUCT_UNIT_SETTING(
    FID            NUMBER(19, 0)    NOT NULL,
    IS_MAINUNIT    NUMBER(1, 0),
    QUOTIETY       FLOAT(7),
    PRODUCT        NUMBER(19, 0),
    UNIT           NUMBER(19, 0),
    CONSTRAINT CPK_PRO_PRODUCT_UNIT_SETTING PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_PRO_PULP 
--

CREATE TABLE CT_PRO_PULP(
    BLEACH_TECHNICS    VARCHAR2(255)    NOT NULL,
    BRAND              VARCHAR2(64)     NOT NULL,
    FIBRE_SOURCE       VARCHAR2(255)    NOT NULL,
    GRADE              VARCHAR2(64)     NOT NULL,
    PULP_TECHNICS      VARCHAR2(255)    NOT NULL,
    FID                NUMBER(19, 0)    NOT NULL,
    CONSTRAINT CPK_PRO_PULP PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_SYS_BASECODE 
--

CREATE TABLE CT_SYS_BASECODE(
    FID            NUMBER(19, 0)     NOT NULL,
    CODE           VARCHAR2(32)      NOT NULL,
    DESCRIPTION    VARCHAR2(4000),
    NAME           VARCHAR2(255),
    TYPE           VARCHAR2(32),
    CONSTRAINT CPK_SYS_BASECODE PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_SYS_PARAMETER 
--

CREATE TABLE CT_SYS_PARAMETER(
    FID            NUMBER(19, 0)    NOT NULL,
    PARAM_ITEM     VARCHAR2(64),
    PARAM_NAME     VARCHAR2(64),
    PARAM_VALUE    VARCHAR2(255),
    CONSTRAINT CPK_SYS_PARAMETER PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_USER_ADMIN 
--

CREATE TABLE CT_USER_ADMIN(
    ADDRESS        VARCHAR2(255),
    DESCRIPTION    VARCHAR2(4000),
    EMAIL          VARCHAR2(64),
    IS_ENBALED     NUMBER(1, 0)      NOT NULL,
    FAX            VARCHAR2(32),
    GENDER         VARCHAR2(32),
    POSTCODE       VARCHAR2(16),
    TELEPHONE      VARCHAR2(32),
    FID            NUMBER(19, 0)     NOT NULL,
    CONSTRAINT CPK_USER_ADMIN PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_USER_FUNCTION 
--

CREATE TABLE CT_USER_FUNCTION(
    FID            NUMBER(19, 0)     NOT NULL,
    CODE           VARCHAR2(32),
    DESCRIPTION    VARCHAR2(4000),
    NAME           VARCHAR2(64),
    PARENT_ID      NUMBER(19, 0),
    CONSTRAINT CPK_USER_FUNCTION PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_USER_FUNCTION_ACTION 
--

CREATE TABLE CT_USER_FUNCTION_ACTION(
    FUNCTION_ID    NUMBER(19, 0),
    ACTION_URL     VARCHAR2(255)
)
;



-- 
-- TABLE: CT_USER_ROLE 
--

CREATE TABLE CT_USER_ROLE(
    FID            NUMBER(19, 0)     NOT NULL,
    CODE           VARCHAR2(32),
    DESCRIPTION    VARCHAR2(4000),
    IS_ENABLED     NUMBER(1, 0),
    NAME           VARCHAR2(64),
    CONSTRAINT CPK_USER_ROLE PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_USER_ROLE_FUNCTION 
--

CREATE TABLE CT_USER_ROLE_FUNCTION(
    CT_USER_ROLE_FID     NUMBER(19, 0)    NOT NULL,
    FUNCTIONITEMS_FID    NUMBER(19, 0)    NOT NULL
)
;



-- 
-- TABLE: CT_USER_USER 
--

CREATE TABLE CT_USER_USER(
    FID         NUMBER(19, 0)    NOT NULL,
    DISC        VARCHAR2(20),
    FULLNAME    VARCHAR2(64)     NOT NULL,
    PASSWORD    VARCHAR2(32),
    USERNAME    VARCHAR2(32)     NOT NULL,
    CONSTRAINT CPK_USER_USER PRIMARY KEY (FID)
)
;



-- 
-- TABLE: CT_USER_USER_ROLE 
--

CREATE TABLE CT_USER_USER_ROLE(
    CT_USER_USER_FID     NUMBER(19, 0)    NOT NULL,
    ASSIGNEDROLES_FID    NUMBER(19, 0)    NOT NULL
)
;



-- 
-- TABLE: CT_ENT_AREA 
--

ALTER TABLE CT_ENT_AREA ADD CONSTRAINT CFK_ENT_AREA_AREA_FID 
    FOREIGN KEY (PARENT_ID)
    REFERENCES CT_ENT_AREA(FID)
;


-- 
-- TABLE: CT_ENT_BRANCH_PRODUCT 
--

ALTER TABLE CT_ENT_BRANCH_PRODUCT ADD CONSTRAINT CFK_ENT_BRAPRO_ENT_FID 
    FOREIGN KEY (BRANCH_ID)
    REFERENCES CT_ENT_ENTERPRISE(FID)
;

ALTER TABLE CT_ENT_BRANCH_PRODUCT ADD CONSTRAINT CFK_ENT_BRAPRO_PRO_FID 
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES CT_PRO_PRODUCT(FID)
;


-- 
-- TABLE: CT_ENT_ENTERPRISE 
--

ALTER TABLE CT_ENT_ENTERPRISE ADD CONSTRAINT CFK_ENT_ENT_AREA_FID 
    FOREIGN KEY (LOCATION_ID)
    REFERENCES CT_ENT_AREA(FID)
;


-- 
-- TABLE: CT_ENT_TRADE_RELATION 
--

ALTER TABLE CT_ENT_TRADE_RELATION ADD CONSTRAINT CFK_ENT_TRARELA_ENT_FID 
    FOREIGN KEY (BRANCH_ID)
    REFERENCES CT_ENT_ENTERPRISE(FID)
;

ALTER TABLE CT_ENT_TRADE_RELATION ADD CONSTRAINT CFK_ENT_TRARELA_PAR_FID 
    FOREIGN KEY (PARTNER_ID)
    REFERENCES CT_ENT_ENTERPRISE(FID)
;


-- 
-- TABLE: CT_PRO_CATEGORY 
--

ALTER TABLE CT_PRO_CATEGORY ADD CONSTRAINT CFK_PRO_CAT_PARENT_FID 
    FOREIGN KEY (PARENT_ID)
    REFERENCES CT_PRO_CATEGORY(FID)
;


-- 
-- TABLE: CT_PRO_CATEGORY_EXTEND 
--

ALTER TABLE CT_PRO_CATEGORY_EXTEND ADD CONSTRAINT CFK_PRO_CATEXT_CAT_FID 
    FOREIGN KEY (CT_PRO_CATEGORY_FID)
    REFERENCES CT_PRO_CATEGORY(FID)
;

ALTER TABLE CT_PRO_CATEGORY_EXTEND ADD CONSTRAINT CFK_PRO_PROEXT_EXT_FID 
    FOREIGN KEY (EXTENDATTRIBUTELIST_FID)
    REFERENCES CT_PRO_EXTEND_ATTRIBUTE(FID)
;


-- 
-- TABLE: CT_PRO_EXTEND_ATTRIBUTE_VALUE 
--

ALTER TABLE CT_PRO_EXTEND_ATTRIBUTE_VALUE ADD CONSTRAINT CFK_PRO_EXTVALUE_EXT_FID 
    FOREIGN KEY (ATTRIBUTE_ID)
    REFERENCES CT_PRO_EXTEND_ATTRIBUTE(FID)
;

ALTER TABLE CT_PRO_EXTEND_ATTRIBUTE_VALUE ADD CONSTRAINT CFK_PRO_EXTVALUE_PRODUCT_FID 
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES CT_PRO_PRODUCT(FID)
;


-- 
-- TABLE: CT_PRO_PAPER 
--

ALTER TABLE CT_PRO_PAPER ADD CONSTRAINT CFK_PRO_PAPER_PRODUCT_FID 
    FOREIGN KEY (FID)
    REFERENCES CT_PRO_PRODUCT(FID)
;


-- 
-- TABLE: CT_PRO_PRODUCT 
--

ALTER TABLE CT_PRO_PRODUCT ADD CONSTRAINT CFK_PRO_PRODUCT_CAT_FID 
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES CT_PRO_CATEGORY(FID)
;


-- 
-- TABLE: CT_PRO_PRODUCT_UNIT_SETTING 
--

ALTER TABLE CT_PRO_PRODUCT_UNIT_SETTING ADD CONSTRAINT CFK_PRO_UNITSET_UNIT_FID 
    FOREIGN KEY (UNIT)
    REFERENCES CT_PRO_MEASURE_UNIT(FID)
;

ALTER TABLE CT_PRO_PRODUCT_UNIT_SETTING ADD CONSTRAINT CFK_UNITSET_PRODUCT_FID 
    FOREIGN KEY (PRODUCT)
    REFERENCES CT_PRO_PRODUCT(FID)
;


-- 
-- TABLE: CT_PRO_PULP 
--

ALTER TABLE CT_PRO_PULP ADD CONSTRAINT CFK_PRO_PULP_PRODUCT_FID 
    FOREIGN KEY (FID)
    REFERENCES CT_PRO_PRODUCT(FID)
;


-- 
-- TABLE: CT_USER_ADMIN 
--

ALTER TABLE CT_USER_ADMIN ADD CONSTRAINT CFK_USER_ADMIN_USER_FID 
    FOREIGN KEY (FID)
    REFERENCES CT_USER_USER(FID)
;


-- 
-- TABLE: CT_USER_FUNCTION 
--

ALTER TABLE CT_USER_FUNCTION ADD CONSTRAINT CFK_USER_FUNC_FUNC_FID 
    FOREIGN KEY (PARENT_ID)
    REFERENCES CT_USER_FUNCTION(FID)
;


-- 
-- TABLE: CT_USER_FUNCTION_ACTION 
--

ALTER TABLE CT_USER_FUNCTION_ACTION ADD CONSTRAINT CFK_USER_FUNCACT_FUNC_FID 
    FOREIGN KEY (FUNCTION_ID)
    REFERENCES CT_USER_FUNCTION(FID)
;


-- 
-- TABLE: CT_USER_ROLE_FUNCTION 
--

ALTER TABLE CT_USER_ROLE_FUNCTION ADD CONSTRAINT CFK_USER_ROLEFUNC_FUNC_FID 
    FOREIGN KEY (FUNCTIONITEMS_FID)
    REFERENCES CT_USER_FUNCTION(FID)
;

ALTER TABLE CT_USER_ROLE_FUNCTION ADD CONSTRAINT CFK_USER_ROLEFUNC_ROLE_FID 
    FOREIGN KEY (CT_USER_ROLE_FID)
    REFERENCES CT_USER_ROLE(FID)
;


-- 
-- TABLE: CT_USER_USER_ROLE 
--

ALTER TABLE CT_USER_USER_ROLE ADD CONSTRAINT CFK_USER_USERROLE_ROLE_FID 
    FOREIGN KEY (ASSIGNEDROLES_FID)
    REFERENCES CT_USER_ROLE(FID)
;

ALTER TABLE CT_USER_USER_ROLE ADD CONSTRAINT CFK_USER_USERROLE_USER_FID 
    FOREIGN KEY (CT_USER_USER_FID)
    REFERENCES CT_USER_USER(FID)
;


